// <auto-generated />
using System;
using GoatFarm.Management.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GoatFarm.Management.Infrastructure.Migrations
{
    [DbContext(typeof(GoatFarmManagementDbContext))]
    [Migration("20220321042727_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GoatFarm.Management.Domain.GoatManagement.Goat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableStatus")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("DateAddedUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<string>("IdentityDescription")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("PictureId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Goat", (string)null);
                });

            modelBuilder.Entity("GoatFarm.Management.Domain.GoatManagement.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("uuid");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFreeToUse")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("TagNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("TagNumber", "FarmId")
                        .IsUnique();

                    b.ToTable("Tag", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("032858ac-44b0-4309-b766-8f0a045ae5da"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "001"
                        },
                        new
                        {
                            Id = new Guid("95e9d0c0-e1cb-40e4-b9d5-4e68237da5f8"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "002"
                        },
                        new
                        {
                            Id = new Guid("b489035d-c495-4d57-af43-f051a0533bce"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "003"
                        },
                        new
                        {
                            Id = new Guid("1cefb659-0b40-4108-a422-21e7c4b8e2bf"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "004"
                        },
                        new
                        {
                            Id = new Guid("ce6a661d-09ee-4b85-93b8-1af0327f1e51"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "005"
                        },
                        new
                        {
                            Id = new Guid("ba1c68aa-a0f9-4445-9a61-b73656949ae6"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "006"
                        },
                        new
                        {
                            Id = new Guid("f0746857-374e-4c16-bd06-21c1ee4c2346"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "007"
                        },
                        new
                        {
                            Id = new Guid("0a4faf59-1f26-48a5-af3d-1589157809d3"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "008"
                        },
                        new
                        {
                            Id = new Guid("348dba5f-02cb-4bb2-85f3-2bddc73075e4"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "009"
                        },
                        new
                        {
                            Id = new Guid("e3ec5c10-884c-46c6-8975-29fe89c004c9"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "010"
                        },
                        new
                        {
                            Id = new Guid("87def534-6eb7-438f-9ef8-34fb4594531d"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "011"
                        },
                        new
                        {
                            Id = new Guid("0d2cf0c9-2b64-4021-afa5-8f236f3e8569"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "012"
                        },
                        new
                        {
                            Id = new Guid("cdc37ea2-6c5b-40c1-b0f1-2efa7ce910af"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "013"
                        },
                        new
                        {
                            Id = new Guid("2ff5d8ea-2d11-4a32-b51b-6582d9a86a36"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "014"
                        },
                        new
                        {
                            Id = new Guid("198e0b6d-5530-4b50-a2a8-977c6dbe8026"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "015"
                        },
                        new
                        {
                            Id = new Guid("1a4c0d76-2ea3-4022-b54e-fae80dcd7734"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "016"
                        },
                        new
                        {
                            Id = new Guid("de95b584-4855-4ee5-ba2c-4596bfeed583"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "017"
                        },
                        new
                        {
                            Id = new Guid("953e91f3-59e7-4036-bbf8-cbab7b0c98dd"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "018"
                        },
                        new
                        {
                            Id = new Guid("217cde3b-ae4f-4f1a-963e-707fb44a8120"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "019"
                        },
                        new
                        {
                            Id = new Guid("5ffc6ee6-112c-43f5-82a6-ba4e4dbab0e7"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "020"
                        },
                        new
                        {
                            Id = new Guid("861bf4c8-552e-4d80-bd45-dadd1c7dd5ba"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "021"
                        },
                        new
                        {
                            Id = new Guid("b3ea2e8e-60a3-47b2-b8a7-a1d093d8e19e"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "022"
                        },
                        new
                        {
                            Id = new Guid("8d667ded-e3f4-4c90-8f72-52c3d16ef282"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "023"
                        },
                        new
                        {
                            Id = new Guid("23fe7156-e357-47f2-80b1-6d1e83484aea"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "024"
                        },
                        new
                        {
                            Id = new Guid("9b0dd1a4-8b03-4029-8982-7fb48b889a53"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "025"
                        },
                        new
                        {
                            Id = new Guid("7365fdc6-ab88-4a49-a274-f2d0a4c913b8"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "026"
                        },
                        new
                        {
                            Id = new Guid("0570ad99-3497-47b5-b077-cfeb472affd3"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "027"
                        },
                        new
                        {
                            Id = new Guid("094d4f01-30dc-479b-83be-376e80c0a17c"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "028"
                        },
                        new
                        {
                            Id = new Guid("8256f1cc-d9b2-4497-8b05-4f7b1b9db46a"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "029"
                        },
                        new
                        {
                            Id = new Guid("72a97e33-219c-48d7-884b-0b4dc9bb6c9e"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "030"
                        },
                        new
                        {
                            Id = new Guid("9191f301-a65b-49a7-b98c-4b022bfc4012"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "031"
                        },
                        new
                        {
                            Id = new Guid("503aabbc-7f64-4811-bf72-96aeb4ddb20c"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "032"
                        },
                        new
                        {
                            Id = new Guid("ff0bf54f-2db2-4499-b97c-56313fc221ba"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "033"
                        },
                        new
                        {
                            Id = new Guid("46e08543-e6c4-4181-8115-6f3d80335221"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "034"
                        },
                        new
                        {
                            Id = new Guid("99c64eda-cc50-4d27-ae0c-04732339aeee"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "035"
                        },
                        new
                        {
                            Id = new Guid("7a0708ed-d0a4-450a-ad22-cbfa1feb734a"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "036"
                        },
                        new
                        {
                            Id = new Guid("08fd2f06-0f44-4c21-a2da-80a789057db1"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "037"
                        },
                        new
                        {
                            Id = new Guid("a54df46d-1874-4dcb-a474-f7983449ba9e"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "038"
                        },
                        new
                        {
                            Id = new Guid("ceb20293-963b-4fc9-b617-b871356a8739"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "039"
                        },
                        new
                        {
                            Id = new Guid("525f169f-26d2-4635-a4b1-f25a0b940cd8"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "040"
                        },
                        new
                        {
                            Id = new Guid("3f25ea0d-3a3a-48ba-b7a3-319c5bc175c8"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "041"
                        },
                        new
                        {
                            Id = new Guid("0e852f8e-0a91-4399-ac4a-57a2dbe6829e"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "042"
                        },
                        new
                        {
                            Id = new Guid("e5091353-1fcb-4675-9961-80bd1f2214a7"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "043"
                        },
                        new
                        {
                            Id = new Guid("620323af-a57d-483f-bc05-69145482be88"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "044"
                        },
                        new
                        {
                            Id = new Guid("e54bc1b7-129e-4b63-9f32-fbe560e47063"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "045"
                        },
                        new
                        {
                            Id = new Guid("9875f2ec-d411-400e-a0da-1c038c63679e"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "046"
                        },
                        new
                        {
                            Id = new Guid("527ffd9a-1ac8-4990-b908-dbbe08f45c90"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "047"
                        },
                        new
                        {
                            Id = new Guid("b01e3558-b783-4be3-a49e-f4e04d96696f"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "048"
                        },
                        new
                        {
                            Id = new Guid("466d5f73-a3a5-41fc-9adf-e02e08527a8f"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "049"
                        },
                        new
                        {
                            Id = new Guid("04c158d9-ce7c-458d-a13e-7a598303f06d"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "050"
                        },
                        new
                        {
                            Id = new Guid("ed455214-be0f-49e6-8e25-d21ea436ff98"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "051"
                        },
                        new
                        {
                            Id = new Guid("97ffef6b-0323-475d-941b-362280d341ac"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "052"
                        },
                        new
                        {
                            Id = new Guid("1864093d-7fe2-49e0-97de-bb3e1c5ff242"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "053"
                        },
                        new
                        {
                            Id = new Guid("a506b4b8-a4f0-412f-a0fd-655c8237f23d"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "054"
                        },
                        new
                        {
                            Id = new Guid("b09e7e50-ce4b-46ea-9527-276c86d9777d"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "055"
                        },
                        new
                        {
                            Id = new Guid("ac418eda-7ce8-41a5-a1ea-211ea005e7a1"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "056"
                        },
                        new
                        {
                            Id = new Guid("0115ce68-2ae8-446f-ade1-e6ac55008faa"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "057"
                        },
                        new
                        {
                            Id = new Guid("8b757f57-ccdd-4e82-8049-7c62c752c6c2"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "058"
                        },
                        new
                        {
                            Id = new Guid("4aaa8412-b03b-448d-99f2-801d443647be"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "059"
                        },
                        new
                        {
                            Id = new Guid("71b30c70-8130-435e-b059-e9f860d8af7c"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "060"
                        },
                        new
                        {
                            Id = new Guid("5c801ff3-202e-4872-a87a-32510368780e"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "061"
                        },
                        new
                        {
                            Id = new Guid("0190664b-d774-44e2-9d03-03dc31d4d0ee"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "062"
                        },
                        new
                        {
                            Id = new Guid("71f0cb98-0664-4ab7-b232-860fb9b7e084"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "063"
                        },
                        new
                        {
                            Id = new Guid("5513123e-ab48-486c-8abe-4ed6708b2aac"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "064"
                        },
                        new
                        {
                            Id = new Guid("92e4ac72-ba43-49df-8d76-edb12e8101ca"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "065"
                        },
                        new
                        {
                            Id = new Guid("dbbf62af-220f-45d9-9be9-761d512074ea"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "066"
                        },
                        new
                        {
                            Id = new Guid("5c1222cf-7482-4e20-b38d-44820c0264fb"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "067"
                        },
                        new
                        {
                            Id = new Guid("8b9cab41-c92b-46ff-aa34-eff916c21c5c"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "068"
                        },
                        new
                        {
                            Id = new Guid("c3f17e70-5adf-479e-87ba-e83999defa8c"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "069"
                        },
                        new
                        {
                            Id = new Guid("2ebd212a-4211-4114-af26-02adb98e9904"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "070"
                        },
                        new
                        {
                            Id = new Guid("7f53eb6a-dcd7-4285-9224-4431930db588"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "071"
                        },
                        new
                        {
                            Id = new Guid("ea68dc3c-246a-4be1-b893-c96cd050570e"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "072"
                        },
                        new
                        {
                            Id = new Guid("f13b848d-428d-4d32-b72e-a98497c2b1e2"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "073"
                        },
                        new
                        {
                            Id = new Guid("186c6740-32b5-4029-a3fc-c4226ee9cba9"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "074"
                        },
                        new
                        {
                            Id = new Guid("6e9771bc-a3db-42f3-93a9-274f227315cf"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "075"
                        },
                        new
                        {
                            Id = new Guid("cceb1c25-10f6-4865-962d-9547c0eb5afd"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "076"
                        },
                        new
                        {
                            Id = new Guid("205f45a4-4077-4758-a2f4-a6ccabacd2af"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "077"
                        },
                        new
                        {
                            Id = new Guid("0451dec8-b463-4d5b-a146-adea138ac6fb"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "078"
                        },
                        new
                        {
                            Id = new Guid("aebf8009-d0bb-451f-b82a-d5a4973fd19c"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "079"
                        },
                        new
                        {
                            Id = new Guid("7ae92b7f-eeb0-40f3-a845-8a716125f961"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "080"
                        },
                        new
                        {
                            Id = new Guid("0920584d-5412-487b-b892-18153529cc3b"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "081"
                        },
                        new
                        {
                            Id = new Guid("419e7c8f-7a65-4543-bc52-2e343349e318"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "082"
                        },
                        new
                        {
                            Id = new Guid("1f458f46-a06c-4588-beb4-e871b643d137"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "083"
                        },
                        new
                        {
                            Id = new Guid("aa2c2e60-8a10-416a-a8d0-1c800b8b086c"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "084"
                        },
                        new
                        {
                            Id = new Guid("c9cd701e-aa6c-4ff5-ad54-8351ff57438c"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "085"
                        },
                        new
                        {
                            Id = new Guid("32b6bc13-6260-4bd4-a98a-6eceb392fb1a"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "086"
                        },
                        new
                        {
                            Id = new Guid("5cb8e013-f810-452c-b213-dbcf2a5629a6"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "087"
                        },
                        new
                        {
                            Id = new Guid("bb4bb404-3142-4165-910c-38f32d0c36d7"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "088"
                        },
                        new
                        {
                            Id = new Guid("552bfb5e-267c-445a-8435-63e0fc8e0660"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "089"
                        },
                        new
                        {
                            Id = new Guid("aebdc35f-71d5-4169-af99-4ff5e6e151c0"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "090"
                        },
                        new
                        {
                            Id = new Guid("a7be25c1-8257-40df-8148-396e0b65e4f4"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "091"
                        },
                        new
                        {
                            Id = new Guid("b9763e79-d181-4fd9-8b9a-2d780bfa422a"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "092"
                        },
                        new
                        {
                            Id = new Guid("c70ed91e-a42a-4632-a58f-9038ef7d00c9"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "093"
                        },
                        new
                        {
                            Id = new Guid("6803d41d-cf75-47a2-8f68-fdbd663f11b9"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "094"
                        },
                        new
                        {
                            Id = new Guid("557ba7ff-6f12-40f6-a906-e0113bd65cb5"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "095"
                        },
                        new
                        {
                            Id = new Guid("2a02c26b-390b-4a0b-81aa-0f61d47f100a"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "096"
                        },
                        new
                        {
                            Id = new Guid("a96d98cd-c520-4f34-84d5-25a2d47aef82"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "097"
                        },
                        new
                        {
                            Id = new Guid("8c17e569-66da-4244-8314-25d433a06a3f"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "098"
                        },
                        new
                        {
                            Id = new Guid("ad8abc9b-563e-44d2-9530-9c7ee1125d4f"),
                            FarmId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            IsFreeToUse = true,
                            TagNumber = "099"
                        });
                });

            modelBuilder.Entity("GoatFarm.Management.Domain.MediaManagement.Picture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Picture", (string)null);
                });

            modelBuilder.Entity("GoatFarm.Management.Domain.TenantManagement.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Farm", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            Name = "Sumarga Farm - Ramkot",
                            TenantId = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3")
                        });
                });

            modelBuilder.Entity("GoatFarm.Management.Domain.TenantManagement.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Tenant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ada750ce-4167-4949-8ca8-f9f2834d40c3"),
                            TenantName = "Sumarga Farm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
